### ISSUE TITLE
1 click colab vinteprotogenmix.ipynb error

### ISSUE THREAD

**Issue by glasseyeartfly** [nolanaatama/sd-1click-colab#13]
I am running into these errors during the launch of this model: vinteprotogenmix.ipynb

"Exception: Error while deserializing header: HeaderTooLarge
Stable diffusion model failed to load, exiting".

The process stops at those lines above, no links to notebooks generated.  Anyone else is running into this problem?  

I am using other models, and they are fine.  I have not tested every model, but the 5 or so ones I use are all fine.

**Comment by glasseyeartfly** [comment]
I looked into the code, and found that the curl lines called for a safetensor file whilst the actual link pointed to a ckpt file.  I changed the curl and mv lines to make sure their names and their links correspond, so now I can load the ckpt file without the headertoolarge error coming up.  If nolan can change those lines and re-upload this ipynb file, everyone should be able to load it up.

**Comment by nolanaatama** [comment]
updated.
thank you for the heads up mate.
