### ISSUE TITLE
not start model

### ISSUE THREAD

**Issue by orangepony4** [nolanaatama/sd-1click-colab#21]
HEAD is now at 0cc0ee1b Merge pull request #7945 from w-e-w/fix-image-downscale
Cloning into 'embeddings'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 32 (delta 4), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (32/32), 4.50 KiB | 329.00 KiB/s, done.
python3: can't open file '/content/stable-diffusion-webui/launch.py': [Errno 2] No such file or directory

the model does not start

**Comment by nolanaatama** [comment]
may you tell me which model you tried to use mate?

**Comment by orangepony4** [comment]
I found out that this is due to the fact that Google Collab has run out of
computing power, and I do not know how to turn on the power of my video
card. so I just create a new Google account and use your neural
network.thank you very much

сб, 11 мар. 2023 г. в 17:30, Nolan Aatama ***@***.***>:

**Comment by nolanaatama** [comment]
is it GPU limit mate? the limit should be restored in around 24 hours and you're right, we could use another account while waiting for the limit to be restored.
anyway, happy to hear if you fixed the issue and have a nice day to you!
