### ISSUE TITLE
New issue, not generating public links

### ISSUE THREAD

**Issue by potato8382** [nolanaatama/sd-1click-colab#23]
Using abyssorangemix3A2,
it only generates a local url, which doesn't open a UI anyway. 
attempted changing remotemoe to cloudflared, no difference.
the output doesnt look any different from usual...

**Comment by Nickode992** [comment]
> Using abyssorangemix3A2, it only generates a local url, which doesn't open a UI anyway. attempted changing remotemoe to cloudflared, no difference. the output doesnt look any different from usual...

Same here. Couldn't get public url using gdrive_lora or chilloutmix

**Comment by potato8382** [comment]
checked again today and all seems to be fine now!

**Comment by nolanaatama** [comment]
I'm not using SD while it happens mate, it seems the issue came from gradio side.
we may try to remove the '--share' from the 'COMMANDLINE_ARGS' code next time if it happens again.
have a nice day!
