### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by X3gold** [nolanaatama/sd-1click-colab#30]
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

**Comment by samvimes23** [comment]
Any fix?

**Comment by Geniu1999** [comment]
same issue
it just stopped working once i lost connection to colab and reconnected with new sesion

**Comment by AmadeusLight** [comment]
same error to me right now

**Comment by ErikAires** [comment]
Same here, I can make a pull request to try to solve it, but I don't have much experience with Jupyter Notebook

**Comment by sanaehirotaka** [comment]
i am also having the same problem.😢
```
Launching Web UI with arguments: --share --disable-safe-unpickle --no-half-vae --xformers --enable-insecure-extension- --gradio-queue --remotemoe
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torchvision/extension.py", line 80, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
```

**Comment by nolanaatama** [comment]
just updated the setups.
you may tell me if it still not working mates

**Comment by X3gold** [comment]
Worked great thank you

**Comment by Sudharma-11** [comment]
Now I am finding the same error
