### ISSUE TITLE
Gradio link does not appear anymore

### ISSUE THREAD

**Issue by doogyhatts** [nolanaatama/sd-1click-colab#44]
I suppose Colab has proceed to end its support for the SD web-ui.
But first, does anyone actually have the same problem as I do?
The gradio link to launch the SD web-ui does not appear anymore because I am not on Pro.

Perhaps it is time for a downgrade to use interactive notebook compute or rent/buy a GPU.

**Comment by Saruvuk** [comment]
I think it's over for free users.

**Comment by nolanaatama** [comment]
gradio is currently down mate.
we still can access the web ui using cloudflare by changing the '!COMMANDLINE' code with this one:

!COMMANDLINE_ARGS="--disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension --gradio-queue --cloudflared" REQS_FILE="requirements.txt" python launch.py

**Comment by doogyhatts** [comment]
thanks for the clarification!
