### ISSUE TITLE
Pickle data was truncated error

### ISSUE THREAD

**Issue by Myocastor** [nolanaatama/sd-1click-colab#5]
What doest that mean? First time seeing this.

 File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: pickle data was truncated

**Comment by nolanaatama** [comment]
just updated all the setup files.
could you tell me if it's working now or not?

**Comment by Myocastor** [comment]
Yeah, it's working now, thank you a lot!
